### PR TITLE
Add CHANGELOG for Passport.

### PR DESCRIPTION
**Pull request by bradgignac**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 67 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-fadf1243e/docs/fanatical-support-aws/). valid for 14 days

**Comment by rackernexus** [comment]
Build 68 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bae320d95/docs/fanatical-support-aws/). valid for 14 days

**Comment by rackernexus** [comment]
Build 69 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-7383d40ef/docs/fanatical-support-aws/). valid for 14 days

**Comment by rackernexus** [comment]
Build 70 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b0d363238/docs/fanatical-support-aws/). valid for 14 days

**Comment by rackernexus** [comment]
Build 71 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-487875c33/docs/fanatical-support-aws/). valid for 14 days

**Pull request merged**
